/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */


//Function: load()
//Called by HTML body element's onload event when the web application is ready to start

var g;
var image;
var pos=0;
function load()
{
	dashcode.setupParts();
	ctx=document.getElementById("canvas").getContext("2d");
	image = ctx.getImageData(0, 0, 320, 240);
	$("#webcam").webcam({
	width: 320,
	height: 240,
	mode: "callback",
	swffile: "jscam.swf",
	onTick: function() {},
	onSave: function(data) {
		//console.log(data);
		var col = data.split(";");
		var img =image;

		for(var i = 0; i < 320; i++) {
			var tmp = parseInt(col[i]);
			img.data[pos + 0] = (tmp >> 16) & 0xff;
			img.data[pos + 1] = (tmp >> 8) & 0xff;
			img.data[pos + 2] = tmp & 0xff;
			img.data[pos + 3] = 0xff;
			pos+= 4;
		}
		if (pos >= 4 * 320 * 240) {
			ctx.putImageData(img, 0, 0);
			gimage=ctx.getImageData(0,0,320,240);
			pos = 0;
			change(null)
		}
	},
	onCapture: function() {},
	debug: function() {},
	onLoad: function() {}
	});
}
var ctx;
var wc;
var gimage;

function change(event)
{
	//get data

	
	var img=ctx.getImageData(0,0,320,240);
	for(var i=0; i<img.data.length; i+=4)
	{
		var r=gimage.data[i+0];
		var g=gimage.data[i+1];
		var b=gimage.data[i+2];
		var a=gimage.data[i+3];
		
		var rplus=255-document.getElementById("R_Slider_A").value;
		var gplus=255-document.getElementById("G_Slider_A").value;
		var bplus=255-document.getElementById("B_Slider_A").value;
		
		r=r-rplus;
		g=g-gplus;
		b=b-bplus;
		
		
		if(document.getElementById("R_Input_B").checked==true)
		{
			r=255-r;
		}
		if(document.getElementById("G_Input_B").checked==true)
		{
			g=255-g;
		}
		if(document.getElementById("B_Input_B").checked==true)
		{
			b=255-b;
		}
		
		if(document.getElementById("Effekt1_Input").checked==true)
		{
			var r1 = Math.floor(Math.random() * 255);
			var r2 = Math.floor(Math.random() * 255);
			var r3 = Math.floor(Math.random() * 255);
			r = Math.floor(r / 255 * r1);
			g = Math.floor(g / 255 * r2);
			b = Math.floor(b / 255 * r3);
		}
		
		img.data[i+0]=r;
		img.data[i+1]=g;
		img.data[i+2]=b;
		img.data[i+3]=a;
		
	}
	
	
	//Write back
	ctx.putImageData(img, 0,0);
	
}










function capture(event)
{
    if(webcam && webcam.capture()==true)
	 {
		webcam.save();
	 }
}
