/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load()
{
    dashcode.setupParts();
	 initCanvas(320,240)
}

var gCtx = null;
var gCanvas = null;

var imageData = null;
var ii=0;
var jj=0;
var c=0;

function pageLoad() { 
	initCanvas(320,240);
} 


function initCanvas(ww,hh)
{
	gCanvas = document.getElementById("canvas");
	var w = ww;
	var h = hh;
	gCanvas.style.width = w + "px";
	gCanvas.style.height = h + "px";
	gCanvas.width = w;
	gCanvas.height = h;
	gCtx = gCanvas.getContext("2d");
	gCtx.clearRect(0, 0, w, h);
	imageData = gCtx.getImageData( 0,0,320,240);
}

function passLine(stringPixels) { 
	//a = (intVal >> 24) & 0xff;

	var coll = stringPixels.split("-");

	var minr=document.getElementById("slider").value;
	var ming=document.getElementById("slider1").value;
	var minb=document.getElementById("slider2").value;

	for(var i=0;i<320;i++) { 
		var intVal = parseInt(coll[i]);
		r = (intVal >> 16) & 0xff;
		g = (intVal >> 8) & 0xff;
		b = (intVal ) & 0xff;
		
		
		imageData.data[c+0]=r-minr;
		imageData.data[c+1]=g-ming;
		imageData.data[c+2]=b-minb;
		imageData.data[c+3]=255;
		
		if(document.getElementById("input").checked==true)
		{
			imageData.data[c+0]=255-imageData.data[c+0];
		}
		
		if(document.getElementById("input1").checked==true)
		{
			imageData.data[c+1]=255-imageData.data[c+1];
		}
		
		if(document.getElementById("input2").checked==true)
		{
			imageData.data[c+2]=255-imageData.data[c+2];
		}
		
		
		c+=4;
	} 

	if(c>=320*240*4) { 
		c=0;
		gCtx.putImageData(imageData, 0,0);
	} 
} 

function captureToCanvas(event) {
	flash = document.getElementById("embedflash");
	flash.ccCapture();
}